// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFUJszFsMUA6iWQTpHJ1VLQatjsioNyr4',
    appId: '1:62751514362:web:b58c2e88c13eb7684bb343',
    messagingSenderId: '62751514362',
    projectId: 'elataar-e87a7',
    authDomain: 'elataar-e87a7.firebaseapp.com',
    storageBucket: 'elataar-e87a7.appspot.com',
    measurementId: 'G-V6HC0HE3HM',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9eGxvWbzd4VKwjYfY81jx5DCM5KqlNE4',
    appId: '1:62751514362:ios:3d5a18506c2a2cd74bb343',
    messagingSenderId: '62751514362',
    projectId: 'elataar-e87a7',
    storageBucket: 'elataar-e87a7.appspot.com',
    iosClientId: '62751514362-k2ota96tkc0cq15l3khq23ensdpuj4dc.apps.googleusercontent.com',
    iosBundleId: 'com.example.elAttarWindows',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFUJszFsMUA6iWQTpHJ1VLQatjsioNyr4',
    appId: '1:62751514362:web:baf265bcbc7530424bb343',
    messagingSenderId: '62751514362',
    projectId: 'elataar-e87a7',
    authDomain: 'elataar-e87a7.firebaseapp.com',
    storageBucket: 'elataar-e87a7.appspot.com',
    measurementId: 'G-35GF71KPL2',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAFUJszFsMUA6iWQTpHJ1VLQatjsioNyr4',
    appId: '1:62751514362:web:4312e0f1db1fb2684bb343',
    messagingSenderId: '62751514362',
    projectId: 'elataar-e87a7',
    authDomain: 'elataar-e87a7.firebaseapp.com',
    storageBucket: 'elataar-e87a7.appspot.com',
    measurementId: 'G-HF0WW9HRCV',
  );
}
